"""Profile model added

Revision ID: d588a2e5a499
Revises: aba1a2a611da
Create Date: 2023-06-24 18:17:49.236974

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd588a2e5a499'
down_revision = 'aba1a2a611da'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('whatsapp', sa.String(length=100), nullable=True),
    sa.Column('cdn', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
